<a href="https://colab.research.google.com/github/Ashwath95/DataScience_Metrials/blob/main/Python_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Operators 
a=10
b=20

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a == b)
print(a != b)
print(a<b)
print(a>b)
print(a<=b)
print((a==a)&(b==b))
print((a <b) | (a > b ))
print(not(a==b))

30
-10
200
0.5
False
True
True
False
True
True
True
True


In [ ]:
#Loops in python 

#While 
#For
#SHIFT +TAB - to out of loop

i=1
while i <=5:
  print(i)
  i=i+1
print("Loop ends")

1
2
3
4
5
Loop ends


In [ ]:

i=1
while i <=5 :
  while i <= 3:
    print(i)
    i=i+1
  i=i+1
print("Loop ends")

1
2
3
Loop ends


In [ ]:
#For loop
for i in range(6):
  print("Hello")

Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
#If statment

import random
from numpy.random import randn as r
# print(random.randint(0,9))
x=r()
print(x)
if r() > 1:
  print("random value is greater than 1")


1.8922875734853202


In [ ]:
#Else Statement
result= None
if r() > 1:
  result="greater than 1"
else:
  result="less than 1"
print(result)

greater than 1


In [ ]:
#elif Statement
result= None

z=int(input())
if z > 1:
  result="greater than 1"
elif z < -1:
  result="less than -1"
else:
  result="between -1 and 1"
print(result)

10
greater than 1


In [ ]:
#List
#we can store any type of data 
#index based
#we can modify list 

l=[1,2,3,4,'abc','good job',True,10.7]
le=len(l)
print(l[::2])

l1=[1,3,4,5,6,7,8]
# print(l[0:len(l1),3])


[1, 3, 'abc', True]


In [ ]:
l=[1,3,4,5,9,2]
print("list:",l)
print("len of list:",len(l))
print("data type:",type(l))
print("max value from list:",max(l))
print("Min value in list:",min(l))

for i in range(len(l)):
  print(l[i],end=' ')

list: [1, 3, 4, 5, 9, 2]
len of list: 6
data type: <class 'list'>
max value from list: 9
Min value in list: 1
1 3 4 5 9 2 

In [ ]:
#Module 
#Module is simple python file which contains variable,methods etc..

In [ ]:
#Numpy
import numpy
print(numpy.array(l))


[1 3 4 5 9 2]


In [87]:

a=numpy.array(l)
print(a.mean())
print(a[::2])
print(a[1::2])
print(max(a))
print(min(a))
print(a[0])
print(a[:])
print(type(a))
b=a
b[0]=10
print(a)
print(b)

4.0
[1 4 9]
[3 5 2]
9
1
1
[1 3 4 5 9 2]
<class 'numpy.ndarray'>
[10  3  4  5  9  2]
[10  3  4  5  9  2]
